#!/bin/bash

for host in \
	mstdn.jp \
	friends.nico \
	pawoo.net \
	mstdn.kemono-friends.info \
	mimumedon.com \
	mastodon.cloud \
	imastodon.net \
	flower.afn.social \
	kirakiratter.com \
	mstdn.osaka \
	vocalodon.net \
	mstdn-workers.com \
	gensokyo.cloud \
	mastodon.nara.jp \
	otajodon.com \
	horiedon.com \
	kabutodon.com \
	mstdn.maud.jp \
	mental.social \
	babuu.club \
	music.pawoo.net \
	3.nu \
	mstdn18.jp \
	bookwor.ms \
	qiitadon.com \
	mstdn.nere9.help \
	julika.jp \
	ika.julika.jp
do
	echo $host
	../../server/distsn-archaeology-instance-speed $host > $host.csv
done


